galaxy_info:
  author: Rory Houlihan
  description: Ansible role to install OpenMediaVault on Raspberry Pi
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - openmediavault
