---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mediaVolume.pv.name }}
spec:
  capacity:
    storage: {{ .Values.volume.mediaVolume.nfs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.mediaVolume.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.mediaVolume.nfs.path }}
    server: {{ .Values.nfsServerIP }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mediaVolume.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: nfs
  accessModes:
    - {{ .Values.mediaVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mediaVolume.nfs.capacity }}
