---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  notify: Restart k3s

- name: Create k3s config dir
  file:
    path: "{{ k3s_server_config_location }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy k3s Config file
  template:
    src: "{{ 'config-init.yaml.j2' if k3s_cluster_init else 'config-join.yaml.j2' }}"
    dest: "{{ k3s_server_config_location }}/config.yaml"
    owner: root
    group: root
    mode: 0644
  notify: Restart k3s

- name: Enable and check K3s service
  systemd:
    name: k3s
    state: started
    enabled: yes

# Ensure k3s is restarted before we attempt to copy the kubeconfig,
# handlers normally fire at end of play so we force them here
- name: Flush handlers
  meta: flush_handlers

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Wait for kubeconfig to exist
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 60

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Replace localhost with master IP in kubeconfig
  replace:
    path: ~{{ ansible_user }}/.kube/config
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ master_ip }}:6443'

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

