---

- name: Add blackbox Helm repo
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Update Helm repo cache
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: cache-refresh
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Ensure blackbox namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ blackbox_namespace }}"

- name: Install/Upgrade blackbox with values.yaml
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: blackbox
    chart_ref: prometheus/prometheus-blackbox-exporter
    chart_version: "{{ chart_version }}"
    release_namespace: "{{ blackbox_namespace }}"
    create_namespace: false
    wait: true
    values_files:
      - "{{ role_path }}/files/values.yaml"
