---

- name: Install nfs specific apt packages
  apt:
    pkg:
      - lvm2
      - nfs-kernel-server
    state: present

- name: Create physical volume & volume group
  lvg:
    vg: "{{ vg_name }}"
    pvs: /dev/sda1
    pesize: 4

- name: Create a backup physical volume & volume group
  lvg:
    vg: backup-vg
    pvs: /dev/sdb1
    pesize: 4

- name: Make nfs root dir
  file:
    path: /mnt/nfs_share
    state: directory
    owner: nobody
    group: nogroup
    mode: '0755'

- include_tasks: roles/nfs/tasks/make_share.yaml
  with_items:
    - jenkins
  loop_control:
    loop_var: share

- name: Restart nfs service service
  systemd:
    state: restarted
    daemon_reload: true
    name: nfs-kernel-server

