---

- name: Create Logical Volume
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ share }}"
    size: 10G

- name: Format Logical Volume
  filesystem:
    fstype: ext4
    dev: "/dev/{{ vg_name }}/{{ share }}"

- name: Create Mount Point
  file:
    path: "{{ nfs_root }}/{{ share }}"
    state: directory
    mode: '0755'

- name: Mount Logical Volume
  mount:
    path: "{{ nfs_root }}/{{ share }}"
    src: "/dev/{{ vg_name }}/{{ share }}"
    fstype: ext4
    state: mounted

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "/dev/{{ vg_name }}/{{ share }}   {{ nfs_root }}/{{ share }}   ext4   defaults   0 0"

- name: Export NFS Share
  lineinfile:
    path: "{{ nfs_share_path }}"
    line: "{{ nfs_root }}/{{ share }} {{ nfs_client_ip }}(rw,sync,no_root_squash,no_all_squash)"
