---

- hosts: all
  become: true
  remote_user: hla
  roles:
    - common

- hosts: nfsservers
  become: true
  remote_user: hla
  roles:
    - openmediavault
  tags: omv

- hosts: k3s_cluster
  gather_facts: yes
  become: true
  remote_user: hla
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
  vars_files:
      - vars/main.yml

- hosts: master
  become: true
  remote_user: hla
  roles:
    - role: k3s/master
  vars_files:
      - vars/main.yml

- hosts: node
  become: true
  remote_user: hla
  roles:
    - role: k3s/node
  vars_files:
      - vars/main.yml

