version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - /mnt/prometheus/data:/prometheus
      - /mnt/prometheus/config:/etc/prometheus
    dns:
      - 192.168.1.15
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.2.0-17027759091
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - /mnt/grafana:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - /etc/letsencrypt/live/houli.eu/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/houli.eu/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - /mnt/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - grafana
    restart: unless-stopped

networks:
  monitoring:
    name: monitoring
    driver: bridge
