---

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Remove nftables
  apt:
    name: nftables
    state: absent
    autoremove: yes
    purge: yes

- name: Install iptables
  apt:
    name: iptables
    state: present

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

