---

# List of machine names and IP addresses
# lib-hp-01.home      192.168.1.96
# lib-potato-01.home  192.168.1.111
# lib-potato-02.home  192.168.1.126
# lib-potato-03.home  192.168.1.195
# lib-potato-04.home  192.168.1.10
# lib-pi-01.home      192.168.1.152
# lib-pi-02.home      192.168.1.207
# lib-pi-03.home      192.168.1.24
# lib-pi-04.home      192.168.1.15

nginx:
  hosts:
    lib-pi-04.home:

pihole:
  hosts:
    lib-pi-04.home:

docker:
  children:
    nginx:
    pihole:

k3smaster:
  hosts:
    lib-potato-02.home:

k3snodes:
  hosts:
    lib-potato-01.home:
    lib-potato-03.home:
    lib-potato-04.home:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:

k3s_cluster:
  children:
    k3smaster:
    k3snodes:

raspbian:
  hosts:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-04.home:
    lib-potato-01.home:
    lib-potato-02.home:
    lib-potato-03.home:
    lib-potato-04.home:

