---

# List of machine names and IP addresses
# lib-hp-01.home      192.168.1.96
# lib-potato-01.home  192.168.1.111
# lib-potato-02.home  192.168.1.126
# lib-potato-03.home  192.168.1.195
# lib-potato-04.home  192.168.1.10
# lib-pi-01.home      192.168.1.152
# lib-pi-02.home      192.168.1.207
# lib-pi-03.home      192.168.1.24
# lib-pi-04.home      192.168.1.15
# lib-pi-05.home      192.168.1.133
# lib-pi-06.home      192.168.1.74

# These nodes sometimes stall for some reason
unstable:
  hosts:
    lib-potato-03.home:

# These are the non k8s nodes that have certbot installed
certbot:
  hosts:
    lib-pi-06.home:

# for Alerts, we need to have an smtp server. It lives on these nodes
smtp_server:
  hosts:
    lib-pi-04.home:

data_service:
  hosts:
    lib-pi-06.home:

node_exporters:
  hosts:
    # lib-hp-o1.home This didn't work so installed manually with apt
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-04.home:
    lib-pi-05.home:
    lib-pi-06.home:
    lib-potato-01.home:
    lib-potato-02.home:
    lib-potato-03.home:
    lib-potato-04.home:

nginx:
  hosts:
    lib-pi-04.home:

pihole:
  hosts:
    lib-pi-04.home:

iscsi_targets:
  hosts:
    lib-pi-06.home:

iscsi_initiators:
  hosts:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-05.home:

docker:
  children:
    nginx:
    pihole:
    data_service:

k3smaster:
  hosts:
    lib-potato-02.home:

k3snodes:
  hosts:
    lib-potato-01.home:
    lib-potato-03.home:
    lib-potato-04.home:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-05.home:

k3s_cluster:
  children:
    k3smaster:
    k3snodes:

raspbian:
  hosts:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-04.home:
    lib-pi-05.home:
    lib-potato-01.home:
    lib-potato-02.home:
    lib-potato-03.home:
    lib-potato-04.home:

ubuntu:
  hosts:
    lib-pi-06.home:
