---

# List of machine names and IP addresses
# lib-potato-01.home  192.168.1.57    // 192.168.1.230
# lib-potato-02.home  192.168.1.156   // 192.168.1.231
# lib-potato-03.home  192.168.1.228   // 192.168.1.232
# lib-potato-04.home  192.168.1.136   // 192.168.1.233
# lib-pi-01.home      192.168.1.152   // 192.168.1.234
# lib-pi-02.home      192.168.1.58    // 192.168.1.235
# lib-pi-03.home      192.168.1.194   // 192.168.1.236
# lib-pi-04.home      192.168.1.15    // 192.168.1.237
# lib-pi-05.home      192.168.1.133   // 192.168.1.238
# lib-pi-06.home      192.168.1.226   // 192.168.1.239
# lib-pi-07.home                      // 192.168.1.240
# lib-hp-01.home      192.168.1.96    // 192.168.1.241
# lib-nuc-01.home     192.168.1.169   // 192.168.1.242

# These nodes sometimes stall for some reason
unstable:
  hosts:
    lib-potato-03.home:

# These are the non k8s nodes that have certbot installed
certbot:
  hosts:
    lib-pi-06.home:

# for Alerts, we need to have an smtp server. It lives on these nodes
smtp_server:
  hosts:
    lib-pi-04.home:

prometheus:
  hosts:
    lib-pi-06.home:

node_exporters:
  hosts:
    # lib-hp-o1.home This didn't work so installed manually with apt
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-04.home:
    lib-pi-05.home:
    lib-pi-06.home:
    lib-potato-01.home:
    lib-potato-02.home:
    lib-potato-03.home:
    lib-potato-04.home:
    lib-nuc-01.home:

nginx:
  hosts:
    lib-pi-04.home:

pihole:
  hosts:
    localhost:

iscsi_targets:
  hosts:
    lib-pi-06.home:

iscsi_initiators:
  hosts:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-05.home:
    lib-nuc-01.home:

longhorn:
  hosts:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    # lib-pi-05.home:
    lib-nuc-01.home:

docker:
  children:
    nginx:
    pihole:
    data_service:

k3smaster:
  hosts:
    lib-potato-02.home:

k3snodes:
  hosts:
    # lib-potato-01.home:
    # lib-potato-03.home:
    lib-potato-04.home:
    lib-pi-01.home:
    # lib-pi-02.home:
    # lib-pi-03.home:
    lib-pi-05.home:
    lib-nuc-01.home:

k3s_cluster:
  children:
    k3smaster:
    k3snodes:

raspbian:
  hosts:
    lib-pi-01.home:
    lib-pi-02.home:
    lib-pi-03.home:
    lib-pi-04.home:
    lib-pi-05.home:
    lib-potato-01.home:
    lib-potato-02.home:
    lib-potato-03.home:
    lib-potato-04.home:

ubuntu:
  hosts:
    lib-pi-06.home:
    lib-nuc-01.home:

pis:
  hosts:
    lib-pi-01.home:
      static_ip: 192.168.1.234
    lib-pi-02.home:
      static_ip: 192.168.1.235
    lib-pi-03.home:
      static_ip: 192.168.1.236
    lib-pi-04.home:
      static_ip: 192.168.1.237
    lib-pi-05.home:
      static_ip: 192.168.1.238
    lib-pi-06.home:
      static_ip: 192.168.1.239
  vars:
    node_type: pi

nucs:
  hosts:
    lib-nuc-01.home:
      static_ip: 192.168.1.242
  vars:
    node_type: nuc

potatoes:
  hosts:
    lib-potato-01.home:
      static_ip: 192.168.1.230
    lib-potato-02.home:
      static_ip: 192.168.1.231
    lib-potato-03.home:
      static_ip: 192.168.1.232
    lib-potato-04.home:
      static_ip: 192.168.1.233
  vars:
    node_type: potato

sbc:
  children:
    pis:
    potatoes:

all_nodes:
  children:
    nucs:
    sbc:

migrate:
  hosts:
    lib-potato-01.home:
