---

- hosts: all
  become: true
  remote_user: hla
  roles:
    - common

- hosts: nfsservers
  become: true
  remote_user: hla
  roles:
    - nfs
  tags: nfs

- hosts: k3s_cluster
  gather_facts: yes
  become: true
  remote_user: hla
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
  vars_files:
      - vars/main.yml

- hosts: k3smaster
  become: true
  remote_user: hla
  roles:
    - role: k3s/master
  vars_files:
      - vars/main.yml

- hosts: k3snodes
  become: true
  remote_user: hla
  roles:
    - role: k3s/node
  vars_files:
      - vars/main.yml

- hosts: docker
  become: true
  remote_user: hla
  roles:
    - role: docker

- hosts: all
  gather_facts: false
  roles:
    - role: ping
  tags: ping

