# This is for hosts that use certbot to renew certificates for nginx
- name: Install certbot packages
  apt:
    pkg:
      - certbot
      - python3-certbot-dns-cloudflare
    state: present
    update_cache: yes

# Make sure the kubeconfig used by the hook exists and is readable
- name: Ensure kubeconfig path exists
  ansible.builtin.file:
    path: "{{ kubeconfig_path }}"
    state: file
    mode: "0600"
  changed_when: false
  failed_when: false

# create a cloudflare api token and put it into the below locations
    # sudo mkdir -p /etc/letsencrypt
    # sudo vim /etc/letsencrypt/cloudflare.ini
# add content
    # dns_cloudflare_api_token = YOUR_CLOUDFLARE_API_TOKEN
# update access
    # sudo chmod 600 /etc/letsencrypt/cloudflare.ini
# run this manually when setting up certbot for the first time on a machine
    # sudo certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d "*.houli.eu"

- name: Ensure certbot.timer is enabled and active
  systemd:
    name: certbot.timer
    enabled: yes
    state: started

# --- Copy scripts from your git repo to the target (only when changed) ---
- name: Copy reload_nginx.sh
  copy:
    src: reload_nginx.sh
    dest: "{{ reload_nginx_path }}"
    owner: root
    group: root
    mode: "0755"
  notify: run-deploy-hook

- name: Copy push-wildcard-to-traefik.sh
  template:
    src: push-wildcard-to-traefik.sh.j2
    dest: "{{ push_k8s_path }}"
    owner: root
    group: root
    mode: "0755"
  notify: run-deploy-hook

- name: Copy copy-certs-to-postgres.sh
  copy:
    src: copy-certs-to-postgres.sh
    dest: "{{ push_postgres_path }}"
    owner: root
    group: root
    mode: "0755"
  notify: run-deploy-hook

- name: Copy unified deploy hook (calls both)
  template:
    src: "cert_renew_deploy.sh.j2"
    dest: "{{ deploy_hook_path }}"
    mode: "0755"

- name: deploy k8s resources
  block:
  - name: Deploy cert-sync rbac
    kubernetes.core.k8s:
      state: present
      src: "{{ role_path }}//files/cert-sync-rbac.yaml"

  - name: Deploy traefik tlsstore
    kubernetes.core.k8s:
      state: present
      src: "{{ role_path }}/files/traefik-tls-store.yaml"

  delegate_to: localhost
  become: false

- name: Wait for cert-sync token to be populated
  command:
    cmd: kubectl -n kube-system get secret cert-sync-token -o jsonpath='{.data.token}'
  register: cert_sync_token
  delegate_to: "{{ k3s_master }}"
  become: true
  retries: 5
  delay: 5
  until: cert_sync_token.stdout != ""

- name: Get cluster CA cert
  slurp:
    src: /var/lib/rancher/k3s/server/tls/server-ca.crt
  register: k3s_ca
  delegate_to: "{{ k3s_master }}"
  become: true

- name: Get cert-sync token
  command:
    cmd: kubectl -n kube-system get secret cert-sync-token -o jsonpath='{.data.token}'
  register: cert_sync_token
  delegate_to: "{{ k3s_master }}"
  become: true

- name: Template kubeconfig to cert host
  template:
    src: config-cert-sync.j2
    dest: "{{ kubeconfig_path }}"
    owner: "{{ ansible_user }}"
    mode: "0600"
