# tls certificate vars
cert_domain: "houli.eu"
cf_ini_path: "/etc/letsencrypt/cloudflare.ini"
deploy_hook_path: "/etc/letsencrypt/renewal-hooks/deploy/50-deploy-shared-cert"
reload_nginx_path: "/usr/local/bin/reload_nginx.sh"
push_postgres_path: "/usr/local/bin/copy-certs-to-postgres.sh"

