---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      name: {{ .Values.pod.name }}
      labels:
        app: {{ .Values.labels.app }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Always
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsUser: {{ .Values.pod.securityContext.runAsUser }}
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-media
              mountPath: /data/media
            - name: radarr-downloads
              mountPath: /data/downloads
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: {{ .Values.configVolume.pvc.name }}
        - name: radarr-media
          persistentVolumeClaim:
            claimName: {{ .Values.mediaVolume.pvc.name }}
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: {{ .Values.downloadsVolume.pvc.name }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: iscsi_initiator
                    operator: In
                    values:
                      - "true"
                  - key: memory
                    operator: In
                    values:
                      - "4.0GB"
