- name: Ensure Nginx config directory exists
  file:
    path: /mnt/nginx
    state: directory
    mode: "0755"

- name: Ensure streams-enable directory exists
  file:
    path: /mnt/nginx/streams-enabled
    state: directory
    mode: "0755"

- name: Copy Nginx config
  template:
    src: nginx.conf.j2
    dest: /mnt/nginx/nginx.conf

- name: Copy Nginx http config
  template:
    src: nginx-http.conf.j2
    dest: /mnt/nginx/nginx-http.conf

- name: Copy streams configs
  template:
    src: postgres-stream.conf.j2
    dest: /mnt/nginx/streams-enabled/postgres.conf

