net_interface: "enp86s0"
netplan_default_file: "/etc/netplan/50-cloud-init.yaml"
k3s_download_url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
k3s_download_checksum: "sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt"
