namespace:
  name: "media"

serviceAccount:
  name: "media-admin"

volume:
  transmission-config:
    path: "/transmission"
    server: "192.168.1.96"
    capacity: "1Gi"
  transmission-pv:
    name: "transmission-pv"
  transmission-pvc:
    name: "transmission-pvc"

transmission:
  image: haugene/transmission-openvpn
  digest: sha256:08e0deef4dc88461c8f8f2cf3ff11d213a00dec4b06d66ca71762956f63fb8c8
  port: 9191

  volume:
    config:
      nfs:
        path: "/transmission"
        server: "192.168.1.96"
        capacity: "1Gi"
      pv: "transmission-pv"
      pvc: "transmission-pvc"
    data:
      nfs:
        path: "/media"
        server: "192.168.1.96"
        capacity: "200Gi"
      pv: "media-pv"
      pvc: "media-pvc"

deployment:
  app:
    name: transmission-openvpn
  name: transmission-deployment
  spec:
    name: transmission-pod
  container:
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "500Mi"
        cpu: "500m"

service:
  name: "transmission-service"

ingress:
  name: "transmission-ingress"
