---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.deployment.app.name }}
  type: ClusterIP
  ports:
    - name: jenkins-port
      protocol: TCP
      port: 8080
      targetPort: 8080
