apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  iscsi:
    targetPortal: 192.168.1.74:3260
    iqn: iqn.2025-02.home.lib-pi-06:lib-pi-06-target
    lun: 5
    fsType: ext4
    readOnly: false
    chapAuthSession: false
  persistentVolumeReclaimPolicy: Retain
