---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.discovery.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: {{ .Values.service.discovery.protocol }}
      port: {{ .Values.service.discovery.port }}
      targetPort: {{ .Values.service.discovery.targetPort }}
      name: {{ .Values.service.discovery.name }}
