---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.http.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: {{ .Values.service.http.name }}
      protocol: {{ .Values.service.http.protocol }}
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
