---
apiVersion: v1
kind: Service
metadata:
  name: tcp-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: {{ .Values.service.web.name }}
      protocol: {{ .Values.service.web.protocol }}
      port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
