---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.tcpdlna.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: {{ .Values.service.tcpdlna.name }}
      protocol: {{ .Values.service.tcpdlna.protocol }}
      port: {{ .Values.service.tcpdlna.port }}
      targetPort: {{ .Values.service.tcpdlna.targetPort }}
