---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.transcodeVolume.pv.name }}
spec:
  capacity:
    storage: {{ .Values.transcodeVolume.capacity }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  iscsi:
    targetPortal: {{ .Values.iscsi.targetIP }}
    iqn: {{ .Values.iscsi.iqn }}
    lun: {{ .Values.transcodeVolume.lun }}
    fsType: ext4
    readOnly: false
    chapAuthSession: false
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.transcodeVolume.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.transcodeVolume.capacity }}
  volumeName: {{ .Values.transcodeVolume.pv.name }}
