---

- name: Ensure download directory exists
  file:
    path: "{{ k3s_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download k3s binary
  get_url:
    url: "{{ k3s_download_url }}"
    checksum: "{{ k3s_download_checksum }}"
    dest: "{{ k3s_download_path }}/k3s"
    owner: root
    group: root
    mode: 0755

