- name: Ensure prometheus compose directory exists
  file:
    path: "{{ compose_file_dir }}"
    state: directory

- name: Setup Volumes
  import_tasks: volume-setup.yaml

- name: Prometheus Setup
  import_tasks: prometheus.yaml

- name: Nginx Setup
  import_tasks: nginx.yaml

- name: Render Docker Compose file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ compose_file_dir }}/docker-compose.yaml"

- name: Run Docker Compose
  command:
    cmd: docker-compose up --force-recreate -d
    chdir: "{{ compose_file_dir }}"
