---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      name: {{ .Values.pod.name }}
      labels:
        app: {{ .Values.labels.app }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Always
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: {{ .Values.configVolume.pvc.name }}
