---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.configVolume.pv.name }}
spec:
  capacity:
    storage: {{ .Values.configVolume.nfs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.configVolume.nfs.path }}
    server: {{ .Values.nfsServerIP }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.configVolume.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.configVolume.nfs.capacity }}
