---

k3s_version: v1.24.17+k3s1
ansible_user: hla
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k3smaster'][0]]['ansible_host'] | default(groups['k3smaster'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
