---

ansible_user: hla
systemd_dir: /etc/systemd/system
k3s_version: v1.24.17+k3s1
master_ip: "{{ hostvars[groups['k3smaster'][0]]['ansible_host'] | default(groups['k3smaster'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
networkmanager_connection_name: ansible-managed
interface: eth0
gateway: 192.168.1.1
dns: 192.168.1.1

