---

# Basic vars
ansible_user: hla
systemd_dir: /etc/systemd/system
networkmanager_connection_name: ansible-managed
gateway: 192.168.1.1
pihole_dns_ip: 192.168.1.15
k3s_pihole_dns_ip: 192.168.1.252

# k3 vars
k3s_version: v1.32.13+k3s1
k3s_download_path: /usr/local/bin
k3s_resolv_conf_location: /etc/rancher/k3s
k3s_server_location: /var/lib/rancher/k3s
master_ip: 192.168.1.249
extra_server_args: ""
extra_agent_args: ""
k3s_master: lib-potato-01.home

# kubectl vars
kubeconfig_path: "{{ lookup('env','KUBECONFIG') | default('~/.kube/config', true) }}"

# Journald vars
journald_system_max_use: "200M"
journald_system_max_file_size: "50M"
journald_max_retention: "7day"

# watchdog vars
watchdog_timeout: 15           # seconds
watchdog_max_load1: 24         # optional extra check

