---

- name: Deploy coredns update to use pihole as upstream
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns-custom
        namespace: kube-system
      data:
        houli.override: |
          forward houli.eu {{ pihole_dns_ip }}
        home.override: |
          forward home {{ pihole_dns_ip }}

- name: Scale CoreDNS to 2 replicas
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coredns
        namespace: kube-system
      spec:
        replicas: 2

- name: Deploy traefik HelmChartConfig update
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ role_path }}/files/traefik-helm-chart-config.yaml"

- name: Apply Traefik Dashboard IngressRoute
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: traefik-dashboard
        namespace: kube-system
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Traefik"
          gethomepage.dev/group: "Infra"
          gethomepage.dev/icon: "traefik"
          gethomepage.dev/description: "Reverse proxy and ingress controller"
      spec:
        entryPoints:
          - websecure
        routes:
          - match: "Host(`{{ traefik_host }}`)"
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
        tls:
          secretName: houli-eu-wildcard

