- name: Assert required inputs present
  assert:
    that:
      - app_name is defined
      - size is defined
      - size | length > 0
    fail_msg: "app_name and size are required (e.g., app_name=grafana size=50G)"

- name: Verify VG exists
  command: "vgs --noheadings -o vg_name {{ vg_name }}"
  register: vg_check
  changed_when: false
  failed_when: vg_check.rc != 0

- name: Verify targetcli present
  command: "targetcli --version"
  register: targetcli_ver
  changed_when: false
  failed_when: targetcli_ver.rc != 0

- name: Normalize size to GiB notation for lvol
  set_fact:
    _normalized_size: "{{ size }}"
