---

- name: Copy Docker Compose file to remote host
  copy:
    src: "./src_files/{{ compose_file_name }}"
    dest: "{{ compose_files_dir }}/pihole/{{ compose_file_name }}"

- name: Start Docker Compose Pihole service
  command: docker compose up --force-recreate -d
  args:
    chdir: "{{ compose_files_dir }}/pihole"
  environment:
    WEBPASSWORD: "{{ PIHOLE_WEBPASSWORD }}"
    TZ: "{{ PIHOLE_TZ }}"

