---

- name: swap esc and caps on wayland
  command: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"
  become_user: "{{ user }}"
  tags:
    - config


- name: make zsh the default shell
  command: chsh -s /bin/zsh
  become_user: "{{ user }}"
  tags:
    - config
