---

- name: Check if systemd-networkd is active
  systemd:
    name: systemd-networkd
  register: networkd_status_dhcp
  failed_when: false

- name: Disable systemd-networkd if dhcpcd is managing the interface
  systemd:
    name: systemd-networkd
    state: stopped
    enabled: false
  when: networkd_status_dhcp.status.ActiveState == "active"

- name: Remove any systemd-networkd config for this interface
  file:
    path: "/etc/systemd/network/{{ interface }}.network"
    state: absent
  when: networkd_status_dhcp.status.ActiveState == "active"

- name: Update dhcpcd.conf
  blockinfile:
    dest: /etc/dhcpcd.conf
    block: |
      interface {{ interface }}
      static routers={{ gateway }}
      static domain_name_servers={{ pihole_dns_ip }}
      static ip_address={{ static_ip }}
    state: present
  notify:
    - Restart dhcpcd

