---

- name: Remove default DHCP netplan config
  file:
    path: "{{ netplan_default_file }}"
    state: absent

- name: Create static IP netplan config
  template:
    src: static-netplan.yaml.j2
    dest: /etc/netplan/10-static.yaml
    owner: root
    group: root
    mode: '0600'
  notify:
    - Apply netplan
