---

- name: Remove Armbian default DHCP netplan config
  file:
    path: /etc/netplan/10-dhcp-all-interfaces.yaml
    state: absent

- name: Create static IP netplan config
  copy:
    dest: /etc/netplan/10-static.yaml
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          end0:
            addresses:
              - {{ static_ip }}/24
            routes:
              - to: default
                via: {{ gateway }}
            nameservers:
              addresses:
                - {{ pihole_dns_ip }}
  notify:
    - Apply netplan
