---

- name: Create systemd-networkd configuration file
  blockinfile:
    path: /etc/systemd/network/01-eth.network
    create: true
    block: |
      [Match]
      Name={{ interface }}

      [Network]
      Address={{ static_ip }}/24
      Gateway={{ gateway }}
      DNS={{ pihole_dns_ip }}
  notify:
    - Restart systemd-networkd
    - Restart systemd-resolved
