apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
  OPENVPN_USERNAME: {{ .Values.openvpn.username | b64enc }}
  OPENVPN_PASSWORD: {{ .Values.openvpn.password | b64enc }}
