---

- name: Install Jenkins into K3s
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - jenkins
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars_files:
    - ../vars/main.yaml
  tags: jenkins
