---

- name: Run Common Operations
  hosts: sbc
  become: true
  roles:
    - common
  vars_files:
    - ../vars/main.yaml
  tags:
    - basic

- name: Move root to ssd
  hosts: sbc
  become: true
  roles:
    - root_storage
  vars_files:
    - ../vars/main.yaml
    - ../vars/root_storage.yaml
  tags:
    - storage

- name: Move root to ssd
  hosts: sbc
  become: true
  roles:
    - root_dir_migrate
  vars_files:
    - ../vars/main.yaml
    - ../vars/root_storage.yaml
  tags:
    - storage

- name: Re-add the boot directory from the sd card
  hosts: potatoes
  become: true
  roles:
    - boot_mount
  vars_files:
    - ../vars/main.yaml
    - ../vars/root_storage.yaml
  tags:
    - storage

- name: Set Static IP
  hosts: sbc
  become: true
  roles:
    - set_static_ip
  vars_files:
    - ../vars/main.yaml
  tags:
    - static_ip


