---

- hosts: iscsi_initiators
  become: true
  remote_user: hla
  roles:
    - common
    - iscsi_initiator
  vars_files:
    - ../vars/main.yaml

- hosts: iscsi_targets
  become: true
  remote_user: hla
  roles:
    - common
    - iscsi_target
  vars_files:
    - ../vars/main.yaml
