---

- name: k3s Prereqs, download and cgroup support
  hosts: k3s_cluster
  become: true
  remote_user: hla
  roles:
    - k3s_prereq
    - download_k3s
    - k3s_cgroup_support
  vars_files:
      - ../vars/main.yaml
  tags:
    - pre
    - init
    - server
    - nodes

- name: Setup initial k3s server
  hosts: k3s_servers[0]
  become: true
  remote_user: hla
  roles:
    - role: k3s/server
      vars:
        k3s_cluster_init: true
    - role: k3s/kube_vip
  vars_files:
    - ../vars/main.yaml
  tags: init

- name: Copy kubeconfig to local
  hosts: k3s_servers[0]
  become: true
  remote_user: hla
  tasks:
    - name: Fetch kubeconfig to local machine
      fetch:
        src: ~{{ ansible_user }}/.kube/config
        dest: ~/.kube/config
        flat: yes
  vars_files:
    - ../vars/main.yaml
  tags: init

- name: Join additional k3s servers
  hosts: k3s_servers[1:]
  become: true
  remote_user: hla
  serial: 1
  roles:
    - role: k3s/server
      vars:
        k3s_cluster_init: false
  vars_files:
    - ../vars/main.yaml
  tags: server

- name: Join k3s worker nodes
  hosts: k3s_workers
  become: true
  remote_user: hla
  roles:
    - role: k3s/worker
  vars_files:
      - ../vars/main.yaml
  tags: nodes

- name: Install cluster infrastructure charts and configure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    # metallb and cert_manager must install before k3s_config
    - metallb
    - cert_manager
    - k3s_config
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars_files:
      - ../vars/main.yaml
  tags:
    - config
