---

- name: Pre tasks
  hosts: node_exporters
  become: true
  roles:
    - common
  vars_files:
      - ../vars/main.yaml

- name: Install Node Exporter on all nodes
  hosts: node_exporters
  become: true
  roles:
    - node_exporter
  vars_files:
      - ../vars/main.yaml

- name: Install Blackbox Exporter into K3s
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - blackbox_exporter

