
---

- name: Pre tasks
  hosts: node_exporters
  become: true
  roles:
    - common
  vars_files:
      - ../vars/main.yaml
  tags:
    - node_exporter
    - blackbox
    - prometheus

- name: Install Node Exporter on all nodes
  hosts: node_exporters
  become: true
  roles:
    - node_exporter
  vars_files:
      - ../vars/main.yaml
  tags: node_exporter

- name: Install Blackbox Exporter into K3s
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - blackbox_exporter
  vars_files:
      - ../vars/main.yaml
  tags: blackbox

- name: Install & Setup Prometheus
  hosts: prometheus
  become: true
  roles:
    - prometheus
  vars_files:
    - ../vars/main.yaml
  tags: prometheus
