---

- name: Install Node Exporter on all nodes
  hosts: all_nodes
  become: true
  roles:
    - node_exporter
  vars_files:
      - ../vars/main.yaml
  tags: node_exporter

- name: Install Blackbox Exporter into K3s
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - blackbox_exporter
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars_files:
      - ../vars/main.yaml
  tags: blackbox

- name: Install & Setup Prometheus
  hosts: prometheus
  become: true
  roles:
    - docker
    - prometheus
  vars_files:
    - ../vars/main.yaml
  tags: prometheus

- name: Install Grafan  into K3s
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - grafana
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars_files:
      - ../vars/main.yaml
  tags: grafana
