---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  notify: Restart k3s

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    state: started
    enabled: yes

- name: Set node name
  set_fact:
    k3s_node_name: "{{ inventory_hostname | regex_replace('\\.home$', '') }}"

