- name: Install apt packages
  apt:
    pkg:
      - vim
      - net-tools
      - lm-sensors
      - python3-pip
    state: present
    update_cache: yes

- name: Disable ssh Password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - restart sshd

- name: Copy rc files
  copy:
    src: "./src_files/{{ item }}"
    dest: "/home/{{ ansible_user }}/{{ item }}"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - .bashrc
    - .vimrc

- name: Mount /tmp as tmpfs
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: "defaults,noatime,mode=1777,size={{ tmpfs_size_mb }}m"
    state: mounted

- name: Ensure en_US.UTF-8 is in /etc/locale.gen
  lineinfile:
    path: /etc/locale.gen
    regexp: '^#?\s*en_US\.UTF-8\s+UTF-8'
    line: "en_US.UTF-8 UTF-8"
    state: present
  register: locale_gen_file

- name: Generate locales
  command: locale-gen
  when: locale_gen_file.changed

- name: Set system locale
  copy:
    dest: /etc/default/locale
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
      LC_CTYPE=en_US.UTF-8
    owner: root
    group: root
    mode: "0644"
