- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install apt packages
  apt:
    pkg:
      - vim
    state: present

- name: Set static IP
  blockinfile:
    dest: /etc/dhcpcd.conf
    block: |
      interface eth0
      static_routers=192.168.1.1
      static domain_name_servers=192.168.1.1
      inform ip_address={{ ansible_default_ipv4.address }}
    state: present
  when: inventory_hostname not in groups.get('ubuntu', [])

- name: Copy rc files
  copy:
    src: "./src_files/{{ item }}"
    dest: "/home/{{ ansible_user }}/{{ item }}"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - .bashrc
    - .vimrc
