---

- name: add extra apt repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:neovim-ppa/unstable


- name: Update and upgrade apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes


- name: Install apt packages
  apt:
    name: "{{ item }}"
  with_items:
    - stow
    - tmux
    - bat
    - fzf
    - kitty
    - rofi
    - vim
    - neovim
    - zsh
    - polybar
    - simple-scan
    - bpython
    - exuberant-ctags
    - htop
    - feh
    - python3-pip
    - python3-virtualenv
    - libreoffice
    - libxcb1-dev
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libev-dev
    - libxcb-cursor-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - autoconf
    - libxcb-xrm0
    - libxcb-xrm-dev
    - automake
    - libxcb-shape0-dev
    - libxcb-xrm-dev
    - xclip
    - libqt5webkit5
    - xutils-dev
    - libtool
    - meson
    - dh-autoreconf
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - xcb
    - libxcb1-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libev-dev
    - libxcb-xkb-dev
    - libxcb-cursor-dev
    - libxkbcommon-dev
    - libxcb-xinerama0-dev
    - libxkbcommon-x11-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libxcb-xrm0
    - libxcb-xrm-dev
    - libxcb-shape0
    - libxcb-shape0-dev
    - chromium-browser
    - picom
    - i3lock
    - scrot
    - imagemagick
    - nomacs
    - libgdk-pixbuf2.0-dev
    - openjdk-11-jdk
    - openjdk-17-jdk
    - openjdk-17-jre
    - arandr
    - fd-find
    - curl
    - vlc
    - sqlite3
# add docker stuff at some point
