---

- name: Update and upgrade apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: add neovim apt repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: Install apt packages
  apt:
    name: "{{ item }}"
  with_items:
    - stow
    - tmux
    - bat
    - fzf
    - kitty
    - rofi
    - vim
    - neovim
    - zsh
    - polybar
    - simple-scan
    - exuberant-ctags
