---

- name: download nvm
  become_user: "{{ user }}"
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: "/home/{{ user }}/Downloads/nvm_install.sh"
    force: yes
    mode: 0764
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - install_packages
    - install_packages.nodejs

- name: install nvm
  become_user: "{{ user }}"
  command:
    chdir: "/home/{{ user }}/Downloads/"
    cmd: ./nvm_install.sh
  tags:
    - install_packages
    - install_packages.nodejs

- name: install nodejs
  become_user: "{{ user }}"
  shell:
    chdir: /home/{{ user }}/.config/nvm/
    cmd: "source nvm.sh && nvm install --lts"
  args:
      executable: /bin/bash
  tags:
    - install_packages
    - install_packages.nodejs
