---
- name: update pip
  pip:
    name: pip
    state: latest
  tags:
    - install_packages
    - install_packages.pip

- name: install pip packages
  become_user: "{{ user }}"
  pip:
    name: "{{ item }}"
  with_items:
    - virtualenvwrapper
    - pynvim
  tags:
    - install_packages
    - install_packages.pip
