version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # To solve conflicting port 53 with systemd-resolved
    # you need to edit the /etc/systemd/resolved.conf and uncomment DNSStubListener
    # and change it to no, so it looks like this: DNSStubListener=no
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
    # Volumes store your data between container upgrades
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)

volumes:
  pihole:
  dnsmasq:

