---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.secret.name }}
type: Opaque
data:
  OPENVPN_USERNAME: {{ .Values.secret.username | b64enc }}
  OPENVPN_PASSWORD: {{ .Values.secret.password | b64enc }}
