# Where to create LVs
pv: "/dev/sda"
vg_name: "vg_k3s_iscsi"

# iSCSI target endpoint (lib-pi-06)
target_portal_ip: "192.168.1.226"
target_portal_port: 3260

# Base IQN prefix. Leave date if you like it as entropy.
iqn_base: "iqn.2025-02.home.lib-pi-06:lib-pi-06-target"

# How we secure access: "acl" (initiator IQNs)
security_mode: "acl"

# If using ACLs, list initiator IQNs (your k3s nodes)
initiator_iqns: []     # e.g. ["iqn.1993-08.org.debian:01:k3s-node-01", "iqn..."]

# Filesystem handling (leave "none" to present raw block and let K8s do it)
fs_type: "ext4"        # or "ext4" / "xfs"
mkfs_args: "-m 0"      # ext4 perf defaults, ignored if fs_type == none

# Naming
lv_name_prefix: "lv_"
backstore_prefix: "bs_"

# Policy
reclaim_policy: "Retain"  # informational; you’ll enforce in PV
expand_if_smaller: true   # grow LV if smaller than requested size
