ingress:
  hosts:
    - host: prowlarr.houli.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ""
      hosts:
        - prowlarr.houli.eu

nodeSelector:
  longhorn-storage: "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node_size
              operator: In
              values: ["medium", "large"]

env:
  TZ: "Europe/Prague"
