ingress:
  hosts:
    - host: prowlarr.houli.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ""
      hosts:
        - prowlarr.houli.eu

nodeSelector:
  longhorn-storage: "true"

env:
  TZ: "Europe/Prague"
