---

- name: Install required packages for Longhorn
  apt:
    name:
      - open-iscsi
      - util-linux
      - nfs-common
      - cryptsetup
    state: present
    update_cache: yes

- name: Load kernel modules for Longhorn
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - nfs
    - dm_crypt

- name: Enable and start iscsid
  systemd:
    name: iscsid
    enabled: yes
    state: started
