---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    tlsStore:
      default:
        defaultCertificate:
          secretName: houli-eu-wildcard
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.1.250
    dashboard:
      enabled: true
    ports:
      traefik:
      # Open up Traefik dashboard port 9000
        expose:
          default: true
      plex-gdm-0:
        port: 32410
        expose:
          default: true
        exposedPort: 32410
        protocol: UDP
      plex-gdm-2:
        port: 32412
        expose:
          default: true
        exposedPort: 32412
        protocol: UDP
      plex-gdm-3:
        port: 32413
        expose:
          default: true
        exposedPort: 32413
        protocol: UDP
      plex-gdm-4:
        port: 32414
        expose:
          default: true
        exposedPort: 32414
        protocol: UDP
      plex-tcp:
        port: 32400
        expose:
          default: true
        exposedPort: 32400
        protocol: TCP
    logs:
      access:
        enabled: true
    entryPoints:
      plex-tcp:
        address: ":32400/tcp"
      plex-gdm-0:
        address: ":32410/udp"
      plex-gdm-2:
        address: ":32412/udp"
      plex-gdm-3:
        address: ":32413/udp"
      plex-gdm-4:
        address: ":32414/udp"
