---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    tlsStore:
      default:
        defaultCertificate:
          secretName: houli-eu-wildcard
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.1.250
    dashboard:
      enabled: true
    ports:
      traefik:
      # Open up Traefik dashboard port 9000
        expose:
          default: true
      plex-tcp:
        port: 32400
        expose:
          default: true
        exposedPort: 32400
        protocol: TCP
    logs:
      access:
        enabled: true
