---
- name: Ensure Prometheus config directory exists
  file:
    path: /mnt/prometheus/config
    state: directory
    owner: 65534  # Nobody user (or change to match container UID)
    group: 65534
    mode: "0755"

- name: Copy Prometheus config to LVM volume
  template:
    src: prometheus.yml.j2
    dest: /mnt/prometheus/config/prometheus.yml

- name: Ensure Prometheus rules directory exists
  file:
    path: /mnt/prometheus/config/rules
    state: directory
    owner: 65534
    group: 65534
    mode: "0755"

- name: Copy alerts config to rules dir in LVM volume
  copy:
    src: alerts.yaml
    dest: /mnt/prometheus/config/rules/alerts.yml

# Ensure Prometheus directories have the correct permissions (owner UID 65534)
- name: Ensure Prometheus directory has correct ownership
  file:
    path: /mnt/prometheus
    owner: 65534
    group: 65534
    recurse: yes

- name: Ensure Nginx config directory exists
  file:
    path: /mnt/nginx
    state: directory
    mode: "0755"

- name: Copy Nginx config to LVM volume
  template:
    src: nginx.conf.j2
    dest: /mnt/nginx/nginx.conf

- name: Ensure monitoring compose directory exists
  file:
    path: "{{ compose_file_dir }}"
    state: directory

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yaml
    dest: "{{ compose_file_dir }}/docker-compose.yaml"

- name: Run Docker Compose
  command:
    cmd: docker-compose up --force-recreate -d
    chdir: "{{ compose_file_dir }}"
