apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: transmission-deployment
  namespace: transmission-ns
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabel:
      app: transmission
  template:
    metadata:
      name: transmission-pod
      labels:
        app: transmission
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: transmission-sa
      containers:
        - name: transmission
          image: haugene/transmission-openvpn
