labels:
  app: transmission-app

namespace:
  name: "transmission"

serviceAccount:
  name: "transmission-admin"

nfsServerIP: "192.168.1.96"

configVolume:
  nfs:
    path: "/transmission"
    capacity: "1Gi"
  pv:
    name: "transmission-pv"
  pvc:
    name: "transmission-pvc"

dataVolume:
  nfs:
    path: "/downloads"
    capacity: "100Gi"
  pv:
    name: "downloads-pv"
  pvc:
    name: "downloads-pvc"

configMap:
  name: "transmission-config"
  openvpnProvider: "PROTONVPN"
  openvpnConfig: "nl.protonvpn.udp"
  localNetwork: "192.168.1.0/24"

deployment:
  name: transmissoin-deployment

pod:
  name: transmission-pod
  securityContext:
    runAsUser: 0

container:
  name: transmission
  image: haugene/transmission-openvpn

secret:
  name: "openvpn-credentials"
  username: "not-a-real-username" # get these from PROTONVPN
  password: "not-a-real-password" # get these from PROTONVPN

service:
  name: "transmission-service"
  portName: http-port
  port: 9091
  targetPort: 9091

ingress:
  name: transmission-ingress
  hostName: transmission.houli.eu
